### ISSUE TITLE
Bring it back. 

### ISSUE THREAD

**Issue by TheFenderStory** [stevoduhhero/YGOSiM#10]
@stevoduhhero give us the images and what not so we can put a working server up, please. Or host it again :)

**Comment by CreaturePhil** [comment]
@stevoduhhero I agree with @TheFenderStory

**Comment by darkson95** [comment]
Would it be possible to give us the images? The hardness of my erection would be unbearable. 🌚

**Comment by TheFenderStory** [comment]
we've been trying to get him to give us those for ever. Might be easier for us to just try and gather them ourselves at this point.

**Comment by stevoduhhero** [comment]
fuck i feel bad now lol

**Comment by CreaturePhil** [comment]
@stevoduhhero are you back now? wanna work on a project together? :rofl:
