### ISSUE TITLE
Another node js Yugioh related project..

### ISSUE THREAD

**Issue by shadowfox87** [stevoduhhero/YGOSiM#11]
Hi, I was wondering if you are interested in helping with YGOPro, the free online automated simulator for Yugioh. We are building a new server in node JS. We have about 7 developers, 2 of them that know node js. We're looking for more node js programmers. If you are interested, reply back. Join the Discord server: http://discord.me/ygopro Let me know what your name is on that server.

**Comment by CreaturePhil** [comment]
@shadowfox87 That's cool. I'm willing to help out. My username on discord is CreaturePhil.

**Comment by shadowfox87** [comment]
I sent you a message on Discord. What's your email?

**Comment by CreaturePhil** [comment]
@shadowfox87 My email is birkal@outlook.com
