### ISSUE TITLE
Project: Online game

### ISSUE THREAD

**Issue by jo-nathan1999** [stevoduhhero/YGOSiM#12]
I was wondering how I would go about creating my own website using YGOSiM

**Comment by CybeX** [comment]
First you need obviously an Server for that.
You mostly just have to follow his steps on how to install it and from there modify it on your own.

(You need to know NodeJS for that)

**Comment by jo-nathan1999** [comment]
Is there any way to add to a WordPress website?

**Comment by stevoduhhero** [comment]
Like into the wordpress db (phpmyadmin)? or the WP admin panel? no
Only if you're okay with reprogramming the user logins using wordpress rest api and handling the node.js express server routes on wordpress too.
The only other way would be to keep them separate and edit your WP .htaccess and then add a subdomain like ygosim.yourwebsite.com

**Comment by stevoduhhero** [comment]
> I was wondering how I would go about creating my own website using YGOSiM
OR you could just learn express and node.js and look into integrating a different CMS [that works with node.js](https://www.sitepoint.com/keystonejs-best-node-js-alternative-wordpress/) and build your site around YGOSiM
